#+title: :cc-langs cpp

* Compile Options
** user-wise
user configuration: a =config.yaml= file in an OS-specific directory:
- =$XDG_CONFIG_HOME/clangd/config.yaml=, typically =~/.config/clangd/config.yaml=
#+begin_src yaml
CompileFlags:
  Add: [-std=c++20]
#+end_src

** project-wise
*** ~cmake~
- Generate =compile_commands.json=
  - ~cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .~
  - both LSP servers and irony will recognize =compile_commands.json=

*** ~clangd~
a file named =.clangd= in the source tree. (clangd searches in all parent directories of the active file).

* Make targets
For a project with a =Makefile=, use ~C-c c b m~ from a C++ buffer to select
and run a project target.  Use ~C-c c b l~ to repeat the most recently selected
target.  The same commands are available in any project as ~M-x +make/run~ and
~M-x +make/run-last~; they prompt for a Makefile when more than one is found.

Use these commands for named project targets such as =build=, =test=, or
=lint=.  Keep ~C-c c c~ for a one-off single-file compile, and use the CMake
commands under ~C-c c b~ for CMake-managed projects.

* Debuggers
- dap-cpptools :: ~M-x dap-cpptools-setup~
- dap-gdb-lldb :: ~M-x dap-gdb-lldb-setup~
- dap-lldb
